# Generated by Django 4.2.5 on 2024-11-10 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('rasm', models.FileField(upload_to='bolimlar')),
            ],
        ),
        migrations.CreateModel(
            name='Ichki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('rasm', models.FileField(upload_to='ichki_bolimlar')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ichkilari', to='asosiyapp.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('brend', models.CharField(max_length=50)),
                ('narx', models.IntegerField()),
                ('batafsil', models.TextField()),
                ('kafolat', models.CharField(max_length=50)),
                ('yetkazish', models.CharField(max_length=50)),
                ('mavjud', models.BooleanField()),
                ('chegirma', models.FloatField()),
                ('ichki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.ichki')),
            ],
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlari', to='asosiyapp.mahsulot')),
            ],
        ),
    ]
